#include <stdio.h>

int main (void)
{
    int contador = 1;

    while(contador <= 10) {

        printf("%s\n", contador % 2 ? "****" : "++++++++");

        contador++;

    }

    return 0;
}

/*

    O PROGAMA IMPRIME A STRING "****" QUANDO O NÚMERO É PAR E A STRING "++++++++" QUANDO O NÚMERO É ÍMPAR.
    A VERIFICAÇÃO É FEITA DE FORMA ANÁLOGA AOS NÚMEROS TIPOS BOOLEANOS, CASO SEJA DIFERENTE DE ZERO É UM
    RESULTADO VERDADEIRO, MAS SE FOR ZERO É UM RESULTADO FALSO.
    ENTÃO, É UTILIZADA UMA ESTRUTURA CONDICIONAL contador % 2, POIS TODO NÚMERO PAR É DIVISÍVEL POR 2, LOGO
    TERÁ RESTO ZERO, ENTÃO O VALOR DESSE RESTO SERÁ LIDO, OU SEJA, O VALOR ZERO QUANDO O NÚMERO É IMPARA,
    IMPRIMINDO A ESTRUTURA FALSA: "++++++++".
    QUANDO O NÚMERO É ÍMPARA, NÃO É DIVISÍVEL POR 2, LOGO O VALOR ATRIBUIDO A CONDIÇÃO SERÁ DIFERENTE DE ZERO,
    PORTANTO A OPÇÃO DE STRING QUE SERÁ IMPRESSA NA TELA SERÁ: "****".
    POR FIM, ESSA IDEIA É TESTADA 10 VEZES EM UMA ESTRUTURA DE REPETIÇÃO WHILE, ONDE ELA FUNCIONARÁ ATÉ QUE A
    VARIÁVEL contador SEJA MENOR OU IGUAL A 10, ESSA QUE TEM UM VALOR ATRIBUIDO INICIALMENTE DE 1, E A CADA
    REPETIÇÃO RECEBE UM INCREMENTO DE 1, GARANTINDO O FUNCIONAMENTO DA ESTRUTURA DE REPETIÇÃO POR SÓ 1O VEZES.

*/
