//UMA FORMA IDEAL PARA REMOVER O COMANDO BREAK DE UM LOOP É UTILIZAR A ESTRUTURA DE DEICSÃO IF/ELSE. OUTRA FORMA DE FAZER ESSE
//PROCESSO, É TORNAR A CONDIÇÃO DA ESTRUTURA DE REPETIÇÃO WHILE VERDADEIRA.
