#include <stdio.h>

int main (void)
{
    int linha = 10;
    int coluna;

    while (linha >= 1) {

        coluna = 1;

        while (coluna <= 10) {

            printf("%s", linha % 2 ? "<" : ">");
            coluna++;

        }

    linha--;

    printf("\n");

    }

    return 0;
}

/*

    PROGAMA QUE IMPRIME UMA SEQUÊNCIA DE STRING ">" 10 VEZES EM UMA LINHA QUANDO O NÚMERO É IMPAR E
IMPRIME UMA SEQUÊNCIA DE STRING "<" 10 VEZES EM UMA LINHA QUANDO O NÚMERO É PAR.

O PROGAMA INICIA A VARIÁVEL TIPO INTEIRA LINHA, ATRIBUINDO-A O VALOR 10, E A VARIÁVEL COLUNA. ENTÃO, É INICIADO UMA
ESTRUTURA DE REPETIÇÃO WHILE, POIS A PARADA DA REPETIÇÃO NÃO ESTÁ NECESSARIAMENTE EXPLÍCITA, MUITO EMBORA SEJA PREVISÍVEL.
DENTRO DESSA ESTRUTURA, É ATRIBUIDO O VALOR 1 A VARÍAVEL COLUNA E OUTRA ESTRUTURA DE REPETIÇÃO WHILE É CRIADO DENTRO DESSA,
A DIFERENÇA É QUE A PRIMEIRA FUNCIONA ENQUANDO A VARIÁVEL LINHA FOR MAIOR OU IGUAL QUE 1, E A EXTERNA FUNCIONA ENQUANNDO A
VARIÁVEL COLUNA FOR MENOR OU IGUAL A 10. DENTRO DA ESTRUTURA DE REPETIÇÃO INTERNA, SEJA IMPRESSO, A STRING "<" OU ">", SEGUNDO
A IDEIA DITA ACIMA, USANDO, PARA ESSE FIM, O MÉTODO DE NÚMEROS BOOLEANOS, EM QUE QUALQUER NÚMERO DIFERENTE DE ZERO É VERDADEIRO
E SENDO IGUAL, É FALSO. AINDA NESSA ESTRUTURA, É INCREMENTADA O VALOR 1 A VARIÁVEL COLUNA A CADA REPETIÇÃO. NA ESTRUTURA DE
REPETIÇÃO EXTERNA, É DECREMENTADO O VALOR 1 DA VARIÁVEL LINHA, E É IMPRESSO NA TELA UM COMANDO DE IR PARA A PRÓXIMA LINHA,
TERMINANDO ENTÃO A ESTRUTURA DE REPETIÇÃO EXTERNA, EM UM CICLO.

*/
