// O COMANDO WHILE VERIFICA PARA DEPOIS EXECUTAR. JÁ O COMANDO DO/WHILE EXECUTA PARA SÓ DEPOIS VERIFICAR. EM OUTRAS PALAVRAS,
//O COMANDO DO/WHILE É EQUIVALENTE AO WHILE, EXETO QUE O DO/WHILE EXECUTA O COMANDO PELO MENOS 1 VEZ.for
//ENTÃO, CASO O PROGAMADOR QUEIRA FAZER UM LOOP COM AMBOS, É NECESÁRIO QUE O PROGAMA EXECUTE ENQUANTO ALGUMA CONDIÇÃO NÃO FOR
//VERDADEIRA, GARANTINDO QUE ESSA CONDIÇÃO PERMANEÇA NESSE ESTADO.
