//UMA FORMA DE REMOVER A ESTRUTURA CONTINUE DE UM LOOP É UTILIZANDO UMA ESTRUTURA DE DECISÃO IF PARA EXECUTAR OS COMANDOS,
//EXCETO AQUELE QUE VOCÊ DESEJA OFUSCAR. TAL QUAL PODERIA SER UTILIZANDO O COMANDO CONTINUE.
